name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE #$NUMBER [@$AUTHOR]"

categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
      - "✨"
      - "⚡️"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
      - "🐛"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
      - "📚"
  - title: " 🚨 Continous Integration"
    labels:
      - "testing"
      - "test"
  - title: " 🔨 Maintance"
    labels:
      - "Maintenance"

exclude-labels:
  - "changelog: skip"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |

  ## whylogs release v$RESOLVED_VERSION
  Hi everyone! We’ve now released whylogs $RESOLVED_VERSION 🚀.
  whylogs is the open standard for data and ML logging created by WhyLabs. 👩🏽‍🔬
  This version includes:

  $CHANGES
